(async()=>{
const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');
const nodes={};const listeners={};const storage={};
const context=vm.createContext({console,Intl,Date,URL,crmSettings:{name:'Admin',organization:'GrantEd',year:2027},renderClientTests:()=>'',setTimeout,clearTimeout,location:{hash:'#clients'},localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v},document:{querySelector:s=>nodes[s]??=(s==='#modal'?{close(){},style:{}}:{style:{}}),addEventListener:(name,fn)=>{(listeners[name]??=[]).push(fn)}},window:{addEventListener(){}},crypto:{randomUUID:()=> 'test-id'},FormData:class{constructor(form){return Object.entries(form.values)}}});
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../dist/reports.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../dist/app.js'),'utf8').replace(/startCRM\(\);\s*$/,'clients=seed();'),context);
const run=s=>vm.runInContext(s,context);const plain=s=>JSON.parse(JSON.stringify(run(s)));
assert.deepEqual(plain("feeTotals([{feeStatus:'paid',feeAmount:0.1,feeCurrency:'USD'},{feeStatus:'paid',feeAmount:0.2,feeCurrency:'USD'},{feeStatus:'paid',feeAmount:80,feeCurrency:'EUR'},{feeStatus:'unpaid',feeAmount:100,feeCurrency:'USD'},{feeStatus:'waived',feeAmount:50,feeCurrency:'USD'},{}])"),[{currency:'EUR',amount:80},{currency:'USD',amount:0.3}]);
for(const value of ['-1','1.001','Infinity','abc'])assert.throws(()=>run(`validateFee({feeStatus:'paid',feeAmount:${JSON.stringify(value)},feeCurrency:'USD'})`));
assert.throws(()=>run("validateFee({feeStatus:'paid',feeAmount:'',feeCurrency:'USD'})"));
assert.equal(run("validateFee({feeStatus:'waived',feeAmount:'90',feeCurrency:'USD'}).feeAmount"),0);
assert.equal(run("validateFee({feeStatus:'unknown',feeAmount:'',feeCurrency:'USD'}).feeAmount"),null);
assert.throws(()=>run("validateFee({feeStatus:'paid',feeAmount:'90',feeCurrency:'USD',feePaidDate:'2099-01-01'})"));
const originalApps=run('JSON.stringify(clients[0].apps)');
run("serverSave=async()=>{localStorage.setItem(KEY,JSON.stringify(clients));return true};render=()=>{}");
const submit=listeners.submit[0];
await submit({preventDefault(){},target:{id:'client-form',dataset:{id:'c1'},values:{name:'Test applicant',email:'test@example.com',phone:'',folder:'',level:'Магистратура',year:'2027',country:'USA',academicField:'IT / Business',semester:'Fall',funding:'Fully Funded and Bolashak',english:'Advanced',exam:'Нет',consultant:'Yernar Kuanyshev',startDate:'2026-07-01'}}});
let saved=JSON.parse(storage['admissions-crm-demo-v1']);assert.equal(saved[0].funding,'Fully Funded and Bolashak');assert.equal(saved[0].startDate,'2026-07-01');assert.equal(JSON.stringify(saved[0].apps),originalApps);
await submit({preventDefault(){},target:{id:'application-form',dataset:{client:'c1',app:'a0-0'},values:{university:'University of Toronto',program:'CS',country:'Canada',deadline:'2027-01-01',status:'Подана',feeAmount:'90.25',feeCurrency:'USD',feeStatus:'paid',feePaidDate:'2026-07-01'}}});
saved=JSON.parse(storage['admissions-crm-demo-v1']);assert.equal(saved[0].apps[0].feeAmount,90.25);assert.equal(saved[0].apps[0].feeStatus,'paid');assert.equal(saved[0].academicField,'IT / Business');
assert.match(run('clientOverview(clients[0])'),/90,25 USD/);assert.match(run('clientOverview(clients[0])'),/Fall · 2027/);
console.log('PASS: currency totals, decimal precision, unpaid/waived exclusion, invalid amounts, date limits, profile + application persistence, existing data preservation.');
const rpt=plain("buildReport(clients[0],{stage:reportStages[0],from:'2026-07-01',to:iso(today),done:'Согласован список.',next:'Подготовить документы.',clientAction:'Уточнить приоритеты.',appIds:['a0-0']})");
assert.equal(rpt.applications.length,1);assert.equal(rpt.appCount,2);assert.equal(rpt.periodFees[0].amount,90.25);assert.equal(rpt.sent,null);assert.equal(rpt.ack,null);assert.equal('notes' in rpt,false);assert.equal('email' in rpt.client,false);
run("clients[0].reports=[buildReport(clients[0],{stage:reportStages[0],from:'2026-07-01',to:iso(today),done:'Итог.',next:'Далее.',clientAction:'Действие.',appIds:['a0-0']})]");
run("clients[0].apps[0].status='Отказ';clients[0].apps[0].feeAmount=200");
assert.equal(run('clients[0].reports[0].applications[0].status'),'Подана');assert.equal(run('clients[0].reports[0].fees[0].amount'),90.25);
assert.throws(()=>run("recordReportEvent(clients[0],'test-id','ack',{date:iso(today),channel:'Email',note:'Ответ клиента'})"));
run("recordReportEvent(clients[0],'test-id','sent',{date:iso(today),channel:'Email'})");
assert.throws(()=>run("recordReportEvent(clients[0],'test-id','ack',{date:iso(today),channel:'Email',note:''})"));
run("recordReportEvent(clients[0],'test-id','ack',{date:iso(today),channel:'Email',note:'Получено подтверждение'})");
assert.equal(run('clients[0].reports[0].ack.source'),'admin_manual');assert.equal(run('reportStatus(clients[0].reports[0])'),'Ознакомление подтверждено');
assert.throws(()=>run("buildReport(clients[0],{stage:reportStages[0],from:'2026-02-31',to:iso(today),done:'a',next:'b',clientAction:'c',appIds:[]})"));
run("clients[0].notes='PRIVATE INTERNAL NOTE';clients[0].reports[0].done='<script>bad()</script>'");
assert.ok(!run('reportPaper(clients[0].reports[0])').includes('PRIVATE INTERNAL NOTE'));assert.ok(run('reportPaper(clients[0].reports[0])').includes('&lt;script&gt;'));
console.log('PASS: immutable report snapshots, period payments, private notes excluded, date validation, escaped text, manual sent/ack transition rules.');

})().catch(e=>{console.error(e);process.exitCode=1});
