const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const {createCanvas}=require('/Users/yernarkuanyshev/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const context=vm.createContext({console,Intl,Date,URL,crmSettings:{name:'Admin',organization:'GrantEd',year:2027},renderClientTests:()=>'',TextEncoder,Uint8Array,setTimeout,clearTimeout,crypto:{randomUUID:()=> 'report-example'},location:{hash:'#clients'},localStorage:{getItem:()=>null},window:{addEventListener(){}},document:{querySelector:()=>({}),addEventListener(){},createElement:type=>{if(type==='canvas')return createCanvas(1,1);throw new Error(type)}}});
for(const file of ['report-pdf.js','reports.js','app.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist',file),'utf8').replace(/initReports\(\);\s*startCRM\(\);\s*$/,''),context);
const run=s=>vm.runInContext(s,context);run('clients=seed()');
run("var sample=buildReport(clients[99],{stage:reportStages[0],from:'2026-09-01',to:iso(today),done:'Демонстрационный пример: согласованы направления поступления и список университетов. Для каждой программы определены требования и следующие действия.',next:'Подготовить резюме и черновик мотивационного письма. Затем согласовать документы и проверить комплектность каждой заявки.',clientAction:'До 10 октября прислать актуальное резюме и перевод транскрипта. Подтвердить ознакомление с отчётом ответным сообщением.',appIds:clients[99].apps.map(a=>a.id)})");
const output=run('renderReportCanvas(sample)');assert.ok(output.fits,`height ${output.usedHeight}`);const jpeg=output.canvas.toBuffer('image/jpeg');context.jpeg=jpeg;context.pixelWidth=output.canvas.width;context.pixelHeight=output.canvas.height;const pdf=run('makeImagePdf(jpeg,pixelWidth,pixelHeight)');fs.mkdirSync(path.join(__dirname,'../output/pdf'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../output/pdf/stage-report-example.pdf'),pdf);
fs.mkdirSync(path.join(__dirname,'../tmp/pdfs'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../tmp/pdfs/report-source.png'),output.canvas.toBuffer('image/png'));
run("sample.done='Длинный текст '.repeat(1500)");assert.equal(run('renderReportCanvas(sample,9).fits'),false);console.log('PASS: A4 PDF generated, normal report fits; overflowing report rejected.');
