import {token,digest,passwordHash,passwordMatches,safeEqual} from './security.mjs';
import {fail} from './validation.mjs';
export function adminService(store){const {db}=store;
 db.exec('CREATE TABLE IF NOT EXISTS recovery(hash TEXT PRIMARY KEY, created TEXT NOT NULL)');
 const get=()=>JSON.parse(db.prepare("SELECT value FROM metadata WHERE key='settings'").get()?.value||'{"name":"Администратор","organization":"GrantEd","year":2027}');
 const admin=()=>db.prepare('SELECT * FROM admin WHERE id=1').get();
 const password=value=>{if(typeof value!=='string'||value.length<12||value.length>256)fail('Пароль должен содержать от 12 до 256 символов.')};
 async function verify(value){const a=admin();if(typeof value!=='string'||value.length>256||!a||!await passwordMatches(value,a.password_hash))fail('Неверный текущий пароль.',401);return a}
 return {status(){return {...get(),email:admin()?.email,recoveryEnabled:!!db.prepare('SELECT hash FROM recovery').get()}},
 update(data){if(typeof data.name!=='string'||!data.name.trim()||data.name.length>100||typeof data.organization!=='string'||!data.organization.trim()||data.organization.length>100||!Number.isInteger(data.year)||data.year<2020||data.year>2100)fail('Проверьте имя, организацию и год набора.');const value={name:data.name.trim(),organization:data.organization.trim(),year:data.year};db.prepare("INSERT OR REPLACE INTO metadata VALUES('settings',?)").run(JSON.stringify(value));store.audit('settings_updated');return value},
 async recovery(currentPassword){const a=await verify(currentPassword);const code=token();db.exec('BEGIN IMMEDIATE');try{if(admin().password_hash!==a.password_hash)fail('Пароль изменился. Войдите повторно.',409);db.prepare('DELETE FROM recovery').run();db.prepare('INSERT INTO recovery VALUES(?,?)').run(digest(code),new Date().toISOString());store.audit('recovery_created');db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return code},
 async change(data){password(data.newPassword);const a=await verify(data.currentPassword);const hash=await passwordHash(data.newPassword);db.exec('BEGIN IMMEDIATE');try{if(admin().password_hash!==a.password_hash)fail('Пароль уже изменён.',409);db.prepare('UPDATE admin SET password_hash=? WHERE id=1').run(hash);db.prepare('DELETE FROM sessions').run();db.prepare('DELETE FROM oauth_states').run();store.audit('password_changed');db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}},
 async reset(data){password(data.newPassword);if(typeof data.code!=='string'||data.code.length>200||typeof data.email!=='string')fail('Неверная почта или резервный код.',400);const codeHash=digest(data.code.trim()),a=admin();if(!a||a.email!==data.email.trim().toLowerCase()||!db.prepare('SELECT hash FROM recovery WHERE hash=?').get(codeHash))fail('Неверная почта или резервный код.',400);const hash=await passwordHash(data.newPassword);db.exec('BEGIN IMMEDIATE');try{if(!db.prepare('SELECT hash FROM recovery WHERE hash=?').get(codeHash)||!safeEqual(admin().password_hash,a.password_hash))fail('Код уже использован или заменён.',400);db.prepare('UPDATE admin SET password_hash=? WHERE id=1').run(hash);db.prepare('DELETE FROM recovery').run();db.prepare('DELETE FROM sessions').run();db.prepare('DELETE FROM oauth_states').run();store.audit('password_recovered');db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
 };
}
