import {createHash} from 'node:crypto';
import {token,digest,encrypt,decrypt} from './security.mjs';
import {fail,validId} from './validation.mjs';
export function googleService(store,origin,{clientId=process.env.GOOGLE_CLIENT_ID,clientSecret=process.env.GOOGLE_CLIENT_SECRET,fetcher=fetch}={}){
 const {db,key}=store,redirect=origin+'/oauth/google/callback';
 const configured=()=>!!(clientId&&clientSecret);
 async function json(url,options){const response=await fetcher(url,{...options,signal:AbortSignal.timeout(15000)});if(!response.ok)fail('Google отклонил запрос. Проверьте разрешения или подключите аккаунт повторно.',502);return response.json()}
 const exchange=params=>json('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,...params})});
 function authorize({kind,client,email},sessionHash){if(!configured())fail('Сначала настройте GOOGLE_CLIENT_ID и GOOGLE_CLIENT_SECRET на сервере.',503);if(!['gmail','drive'].includes(kind))fail('Неизвестное подключение.');if(kind==='gmail'&&(!validId(client)||!store.getState().clients.some(c=>c.id===client)))fail('Клиент не найден.');if(typeof email!=='string'||!/^\S+@\S+\.\S+$/.test(email))fail('Укажите почту подключаемого Google-аккаунта.');const owner=kind==='drive'?'drive-admin':'gmail-'+client,state=token(),verifier=token();db.prepare('DELETE FROM oauth_states WHERE expires<? OR owner=?').run(Date.now(),owner);db.prepare('INSERT INTO oauth_states VALUES(?,?,?,?,?,?)').run(digest(state),owner,kind,JSON.stringify({verifier,sessionHash}),email.toLowerCase(),Date.now()+600000);const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:clientId,redirect_uri:redirect,response_type:'code',scope:'openid email '+(kind==='gmail'?'https://www.googleapis.com/auth/gmail.readonly':'https://www.googleapis.com/auth/drive.metadata.readonly'),state,access_type:'offline',prompt:'consent',login_hint:email,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'});return url.href}
 async function callback(params,sessionHash){const state=db.prepare('SELECT * FROM oauth_states WHERE state_hash=? AND expires>?').get(digest(params.get('state')||''),Date.now());if(!state)fail('Ссылка подключения истекла. Начните заново.',400);const binding=JSON.parse(state.verifier);if(binding.sessionHash!==sessionHash)fail('Вернитесь в браузер, где начато подключение.',403);db.prepare('DELETE FROM oauth_states WHERE state_hash=?').run(state.state_hash);if(params.get('error')||!params.get('code'))fail('Подключение Google отменено.');const tokens=await exchange({code:params.get('code'),code_verifier:binding.verifier,redirect_uri:redirect,grant_type:'authorization_code'});const user=await json('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:'Bearer '+tokens.access_token}});if(!user.email_verified||user.email?.toLowerCase()!==state.expected_email)fail('Выбран другой Google-аккаунт. Повторите подключение с указанной почтой.');if(state.kind==='gmail'&&!store.getState().clients.some(c=>'gmail-'+c.id===state.owner))fail('Карточка клиента больше не существует.');tokens.expires_at=Date.now()+tokens.expires_in*1000;db.prepare('INSERT OR REPLACE INTO connections VALUES(?,?,?,?)').run(state.owner,user.email,state.kind,encrypt(tokens,key));store.audit('google_connected',state.owner);return state.kind==='drive'?'integrations':'client/'+state.owner.slice(6)+'/mail'}
 async function access(owner){const row=db.prepare('SELECT * FROM connections WHERE owner=?').get(owner);if(!row)fail('Google-аккаунт не подключён.',409);let tokens=decrypt(row.tokens,key);if(tokens.expires_at<Date.now()+60000){if(!tokens.refresh_token)fail('Подключите Google-аккаунт повторно.',409);const next=await exchange({grant_type:'refresh_token',refresh_token:tokens.refresh_token});tokens={...tokens,...next,expires_at:Date.now()+next.expires_in*1000};db.prepare('UPDATE connections SET tokens=? WHERE owner=?').run(encrypt(tokens,key),owner)}return tokens.access_token}
 async function get(owner,url){return json(url,{headers:{Authorization:'Bearer '+await access(owner)}})}
 return {configured,authorize,callback,status:()=>({configured:configured(),connections:db.prepare('SELECT owner,email,kind FROM connections').all()}),disconnect(owner){db.prepare('DELETE FROM connections WHERE owner=?').run(owner);store.audit('google_disconnected',owner)},async messages(client){if(!validId(client))fail('Некорректный клиент.');const owner='gmail-'+client,list=await get(owner,'https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=20');const messages=await Promise.all((list.messages||[]).map(m=>get(owner,'https://gmail.googleapis.com/gmail/v1/users/me/messages/'+encodeURIComponent(m.id)+'?format=metadata&metadataHeaders=Subject&metadataHeaders=From&metadataHeaders=Date')));return {messages:messages.map(m=>({id:m.id,snippet:m.snippet,headers:m.payload?.headers||[]}))}},async files(client){const c=store.getState().clients.find(c=>c.id===client);const folder=c?.folder?.match(/\/folders\/([a-zA-Z0-9_-]+)/)?.[1];if(!folder)fail('Добавьте ссылку на папку Google Drive в карточке.');const url=new URL('https://www.googleapis.com/drive/v3/files');url.search=new URLSearchParams({q:`'${folder}' in parents and trashed = false`,fields:'files(id,name,mimeType,webViewLink),nextPageToken',pageSize:'100',orderBy:'name'});return get('drive-admin',url.href)}};
}
