export function fail(message,status=400){throw Object.assign(Error(message),{status})}
const statuses=['Подбор программы','Документы','Подана','Интервью','Оффер','Отказ'];
const idPattern=/^[a-zA-Z0-9_-]{1,100}$/;
export function validId(value){return typeof value==='string'&&idPattern.test(value)}
function text(value,max=20000){return typeof value==='string'&&value.length<=max}
export function validateClients(clients,existing=[]){if(!Array.isArray(clients)||clients.length>2000)fail('Допускается до 2000 клиентов.');const ids=new Set();for(const c of clients){if(!c||!validId(c.id)||ids.has(c.id)||!text(c.name,100)||!c.name.trim())fail('Некорректная карточка клиента или повторяющийся ID.');ids.add(c.id);validateTests(c.tests);if(!['Бакалавриат','Магистратура','PhD'].includes(c.level)||!Number.isInteger(c.year)||c.year<2020||c.year>2100)fail('Проверьте уровень и год поступления.');for(const field of ['email','phone','country','folder','academicField','semester','funding','english','exam','consultant','startDate','notes','gmailEmail'])if(c[field]!==undefined&&!text(c[field],field==='notes'?20000:1000))fail(`Некорректное поле: ${field}`);
 for(const field of ['apps','tasks','docs'])if(!Array.isArray(c[field])||c[field].length>1000)fail(`Некорректный список ${field}`);
 for(const list of [c.apps,c.tasks,c.docs,c.reports||[]]){if(!Array.isArray(list)||list.length>1000)fail('Слишком много записей.');const keys=new Set();for(const entry of list){if(!entry||!validId(entry.id)||keys.has(entry.id))fail('Некорректный ID записи.');keys.add(entry.id)}}
 for(const a of c.apps){if(!text(a.university,160)||!text(a.program,160)||!text(a.country,80)||!statuses.includes(a.status)||!text(a.deadline,10))fail('Некорректная заявка.');if(a.feeAmount!==undefined&&a.feeAmount!==null&&(!Number.isFinite(a.feeAmount)||a.feeAmount<0||a.feeAmount>10000000||Math.abs(a.feeAmount*100-Math.round(a.feeAmount*100))>1e-6))fail('Некорректная сумма application fee.');if(a.feeStatus&&!['unknown','unpaid','paid','waived'].includes(a.feeStatus))fail('Некорректный статус оплаты.');if(a.feeStatus==='paid'&&(a.feeAmount===null||a.feeAmount===undefined))fail('У оплаченного сбора должна быть сумма.');if(a.feeCurrency&&!['USD','EUR','GBP','CAD','AUD','CHF','KZT'].includes(a.feeCurrency))fail('Некорректная валюта.');}
 for(const t of c.tasks)if(!text(t.title,250)||!text(t.date,10)||typeof t.done!=='boolean')fail('Некорректная задача.');
 for(const d of c.docs){if(!text(d.name,160)||!text(d.type,100))fail('Некорректный документ.');try{const u=new URL(d.url);if(u.protocol!=='https:'||!['drive.google.com','docs.google.com'].includes(u.hostname))fail('Неверная ссылка документа.')}catch{fail('Неверная ссылка документа.')}}
 const prior=existing.find(x=>x.id===c.id);for(const r of c.reports||[]){if(!r.client||!text(r.client.name,100)||!text(r.stage,100)||!text(r.done,500)||!text(r.next,400)||!text(r.clientAction,300)||!Array.isArray(r.applications)||r.applications.length>8||!Array.isArray(r.fees)||!Array.isArray(r.periodFees)||!text(r.createdAt,40)||!text(r.from,10)||!text(r.to,10))fail('Некорректный отчёт.');const old=prior?.reports?.find(x=>x.id===r.id);if(old){const snapshot=v=>{const {sent,ack,...rest}=v;return JSON.stringify(rest)};if(snapshot(old)!==snapshot(r))fail('Содержание сохранённого отчёта нельзя изменить. Создайте новый отчёт.');if(old.ack?.source==='client_link'&&JSON.stringify(old.ack)!==JSON.stringify(r.ack))fail('Подтверждение клиента нельзя изменить. Обновите данные.',409)}}
 }return clients}
export function validateTests(tests){if(tests===undefined)return;if(!Array.isArray(tests)||tests.length>200)fail('Допускается до 200 результатов тестов.');const scales={IELTS:[0,9,.5],TOEFL:[1,6,.5],'TOEFL-120':[0,120,1],DET:[10,160,5]},ids=new Set();for(const t of tests){if(!t||!validId(t.id)||ids.has(t.id)||!Object.hasOwn(scales,t.type))fail('Некорректный тест.');ids.add(t.id);const [min,max,step]=scales[t.type];if(typeof t.score!=='number'||!Number.isFinite(t.score)||t.score<min||t.score>max||!Number.isInteger((t.score-min)/step))fail('Балл не соответствует шкале теста.');if(typeof t.date!=='string')fail('Некорректная дата теста.');if(t.date&&(!/^\d{4}-\d{2}-\d{2}$/.test(t.date)||!Number.isFinite(Date.parse(t.date))||new Date(t.date).toISOString().slice(0,10)!==t.date||t.date>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Almaty',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())))fail('Дата теста должна быть корректной и не позже сегодня.')}}
