name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm test

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      OWNER: yernarkuanysh-tech
      IMAGE: crm
      TAG: latest

    steps:
      - uses: actions/checkout@v4

      - name: login ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin

      - name: build image
        run: docker build -t ghcr.io/$OWNER/$IMAGE:$TAG .

      - name: push image to registry
        run: docker push ghcr.io/$OWNER/$IMAGE:$TAG
      
      - name: deploy to cloud
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
          -H "Authorization: Bearer ${{secrets.RAILWAY_TOKEN}}" \
          -H "Content-Type: application/json" \
          -d '{"query":"mutation serviceInstanceRedeploy($serviceId: String!, $environmentId: String!) {serviceInstanceRedeploy(serviceId:$serviceId,environmentId:$environmentId)}","variables":{"serviceId":"${{secrets.RAILWAY_SERVICE_ID}}","environmentId":"${{secrets.RAILWAY_ENVIRONMENT_ID}}"}}'
